apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: config
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ${IMAGE_REPOSITORY}/config
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: config
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/config.yaml